# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install pytest
          command: pip install pytest
      - run:
          name: run hash service tests
          command: | 
            cd get-hash-service
            pytest
      - run:
          name: run html service tests
          command: | 
            cd get-html-service
            pytest
      